apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hash-service.fullname" . }}-config
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.tracing.endpoint }}"
  OTEL_SERVICE_NAME: "{{ .Values.tracing.serviceName }}"
